[Nginx]
172.31.21.94 ansible_ssh_user='ubuntu'

# [Todo]
# private IP ansible_ssh_user='ec2-user'

[Tooling]
172.31.18.179 ansible_ssh_user='ec2-user'
172.31.16.202 ansible_ssh_user= 'ec2-user'

[db]
172.31.24.240 ansible_ssh_user= 'ubuntu'

# [db:vars]
# ansible_user=ec2-user
# ansible_python_interpreter=/usr/bin/python
