[lb]
172.31.18.75 ansible_ssh_user=ubuntu

[webservers]
172.31.17.206 ansible_ssh_user=ec2-user
172.31.27.78 ansible_ssh_user=ec2-user

[db]
172.31.24.240 ansible_ssh_user=ubuntu

[db:vars]
ansible_user=ubuntu
ansible_python_interpreter=/usr/bin/python3
