pipeline {
    agent any
    
    parameters {
        string(name: 'ARTIFACT_VERSION', defaultValue: '1.0.0', description: 'Incoming immutable application build version string')
    }
    
    stages {
        stage('SCM Infrastructure Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Execute Ansible Playbook Deployment') {
            steps {
                // FIXED PATH EXCEPTION: Pointing the orchestrator directly to the playbooks/ subfolder track
                sh "ansible-playbook -i inventory/dev playbooks/site.yml --extra-vars 'version=${params.ARTIFACT_VERSION}'"
            }
        }
    }
}

