---
- name: Configure Webservers
  hosts: webservers
  tags:
    - webserver
  roles:
    - webserver

- name: Include dynamic environment variables
  import_playbook: ../dynamic-assignments/env-vars.yml
  ignore_unreachable: true

- name: Import webserver assignment
  import_playbook: ../static-assignments/common.yml
  ignore_unreachable: true

- name: Import load balancer assignment
  import_playbook: ../static-assignments/loadbalancers.yml
  ignore_unreachable: true

- name: Import db-server assignment
  import_playbook: ../static-assignments/db-servers.yml
  ignore_unreachable: true
